export type CodeShowcaseEntry = {
  slug: string;
  project: string;
  category: string;
  date: string;
  title: string;
  framing: string[];
  codeBlocks: { language: string; code: string }[];
  theFix: string[];
  whyThisMatters: string[];
};

// Real, verified code from the Farpost project — see
// docs/farpost-devlog-handoff-robinsamways.md for the raw source material
// this was written from. Entry 1 is the approved template (pasted as the
// handoff specifies); entries 2-10 are written from that handoff's context
// notes, not pasted as-is.
export const CODE_SHOWCASE_ENTRIES: CodeShowcaseEntry[] = [
  {
    slug: "silent-slug-collision",
    project: "Farpost",
    category: "Data Ingestion",
    date: "2026-07-15",
    title: "The Bug That Silently Ate 2,706 Records",
    framing: [
      "I was loading 31,152 real civic addresses into a MongoDB collection, in batches, for performance — one round-trip per record was too slow against the dataset size. Each building gets a human-readable slug (e.g. 136-spence-rd-carl-civic), generated by checking the database for anything already using that slug and appending -2, -3, etc. on a collision.",
      "That check has a blind spot: it only sees what's already committed to the database. Two addresses distinguished only by a house-number suffix — 136A Spence Rd and 136B Spence Rd — landed in the same unflushed batch. Neither was in the database yet, so both passed the uniqueness check and were assigned the identical slug. The second one failed at insert time with a duplicate-key error — which looked exactly like the expected, harmless case of re-running the pipeline against data it had already loaded. My error handling treated every duplicate-key error the same way: swallow it and move on. 2,706 real addresses quietly vanished before anyone noticed.",
    ],
    codeBlocks: [
      {
        language: "python",
        code: `async def _generate_building_slug(record: dict, assigned_slugs: set[str]) -> str:
    """assigned_slugs tracks every slug handed out so far *this run*, checked in
    addition to the DB. Without it, two records sharing house_no+rd_name+municipality
    (distinguished only by house_suf/rd_dir/unit — e.g. 136A vs 136B Spence Rd) that
    land in the same unflushed batch both pass the \`await Building.find_one\` check
    (neither is in the DB yet) and get assigned the same base slug; the second then
    fails at flush time with a duplicate-key error on the slug index, which looked
    identical to an expected re-run duplicate and was silently swallowed — silently
    dropping 2,706 real records on the first live run before this fix."""
    base = _slugify_component(
        f"{record['house_no']}-{record['house_suf']}-{record['rd_dir']}-{record['rd_name']}-"
        f"{record['unit']}-{record['municipality_code']}-civic",
    ) or "civic-building"
    slug = base
    counter = 2
    while slug in assigned_slugs or await Building.find_one({"slug": slug}):
        slug = f"{base}-{counter}"
        counter += 1
    assigned_slugs.add(slug)
    return slug`,
      },
      {
        language: "python",
        code: `except BulkWriteError as e:
    write_errors = e.details.get("writeErrors", [])
    non_id_duplicates = [
        err for err in write_errors
        if err.get("code") != 11000 or "index: _id_" not in err.get("errmsg", "")
    ]
    if non_id_duplicates:
        raise  # a real bug, not idempotency — must not be swallowed
    inserted = e.details.get("nInserted", batch_size - len(write_errors))`,
      },
    ],
    theFix: [
      "The fix has two parts: (1) track every slug already handed out during this run, in memory, not just what's already in the database — closing the race between unflushed records in the same batch. (2) Stop treating every duplicate-key error the same way — only a duplicate on the _id index is the expected, harmless \"already ingested this\" case. A duplicate on any other index, like slug, is a real data-loss bug wearing the same error code as a harmless one, and now raises instead of vanishing silently.",
    ],
    whyThisMatters: [
      "The dangerous part of this bug wasn't the collision itself — it's that the failure mode was indistinguishable from correct behavior at a glance. \"Duplicate key error, skip it\" is right 99% of the time in an idempotent pipeline. Catching the 1% required actually reasoning about which index the duplicate was on, not just the error code. Caught this during verification before it shipped, by checking the actual record count against the expected one rather than trusting a clean exit code.",
    ],
  },
  {
    slug: "generic-dispatch-loop",
    project: "Farpost",
    category: "Dispatch Architecture",
    date: "2026-07-15",
    title: "A Generic Dispatch Loop, Built Before It Needed to Be",
    framing: [
      "Farpost dispatches work to professionals — claims first, with inspections and other request types planned to follow. Rather than write a claim-specific dispatch function and duplicate it later for inspections, the dispatch loop was built once, against a generic \"dispatchable request\" shape, before a second consumer of it existed.",
      "The subtle part is how it decides who's already been tried. Reputation-based ranking is live — a professional's position in the list can shift between attempts — so re-dispatch has to exclude candidates who already tried by who they are, not by where they landed in the last ranking. Get that backwards, and a re-rank between attempts can silently skip the wrong person.",
    ],
    codeBlocks: [
      {
        language: "python",
        code: `async def dispatch_work_request(
    request: DispatchableRequest,
    notify: NotifyCallable,
) -> None:
    """Core dispatch loop. Called via asyncio.create_task — never awaited directly.

    1. Find eligible candidates
    2. Rank by reputation
    3. Exclude already-tried candidates by identity (not ranking position — ranking
       can shift between attempts since it's reputation-based and live)
    4. Create WorkRequestAttempt
    5. Increment attempt counter on request
    6. Call notify(candidate, attempt)
    7. Schedule an instant in-process timeout check (supplements, doesn't replace,
       the periodic check_request_timeouts sweep)
    """
    repo = WorkRequestAttemptRepository()

    candidates = await find_candidates(
        request.postal_prefix, request.target_role, request.required_capabilities
    )

    if not candidates:
        await request.on_no_candidates()
        return

    ranked = await rank_candidates(candidates)

    existing_attempts = await repo.list_for_request(request.request_id)
    already_tried = {a.candidate_slug for a in existing_attempts}
    eligible = [c for c in ranked if c.slug not in already_tried]

    if not eligible:
        await request.on_all_exhausted()
        return

    candidate = eligible[0]
    # ... create WorkRequestAttempt, notify(candidate, attempt) ...

    asyncio.get_event_loop().call_later(
        request.timeout_minutes * 60,
        lambda: asyncio.create_task(_check_attempt_timeout(str(attempt.id))),
    )`,
      },
    ],
    theFix: [
      "already_tried is built from each attempt's candidate_slug — a stable identity — and checked against ranked candidates by that same slug, not by list index. Two independent completion checks both converge on the same WorkRequestAttemptRepository: an in-process timer scheduled the moment a candidate is notified, and a separate periodic sweep. If both fire for the same attempt, the second one finds nothing left to do and becomes a no-op rather than dispatching twice.",
    ],
    whyThisMatters: [
      "This is what generalizing infrastructure looks like when it's done deliberately rather than forced: a structural Protocol type let inspections and future request types plug into the same dispatch loop with no shared base class, and the exclusion-by-identity detail — easy to get wrong on a live, reordering ranking — was correct on the first pass. That's judgment under ambiguity: building for a second consumer that doesn't exist yet, without guessing wrong about the one subtle correctness detail that would matter once it did.",
    ],
  },
  {
    slug: "reputation-signal-floors",
    project: "Farpost",
    category: "Reputation Scoring",
    date: "2026-07-15",
    title: "Scoring a Blank Slate Without Lying About It",
    framing: [
      "Reputation-based dispatch ranks candidates by their track record — but a brand-new professional with zero history has no track record to rank. The naive fix is to score every unknown dimension as a flat, neutral 0.5 and call it fair. Farpost doesn't do that.",
      "Each signal gets its own honest floor instead: recent activity floors at 0.3, not 0.5 — someone with no activity history isn't assumed to be exactly average, they're assumed slightly below it until proven otherwise. Engagement and experience floor at 0.0, since there's nothing to credit yet. The one place a flat 0.5 does appear is deliberately narrow: only when the reputation computation itself throws an exception, which is a different situation — a broken calculation, not an absence of history — and the code says so in a comment.",
    ],
    codeBlocks: [
      {
        language: "python",
        code: `async def rank_candidates(candidates: list[Professional]) -> list[Professional]:
    """Rank candidates by reputation signals. Role-agnostic.

    Uses the reputation timeline read-model. Professionals with no history are not
    flatly neutral — each signal has its own floor: recently_active=0.3,
    engagement=0.0, experience=0.0, availability computed as normal from real
    capacity fields. Only the \`except\` fallback below (a timeline-computation
    error, not "no history") uses a flat 0.5.
    """
    scored = []
    for pro in candidates:
        try:
            timeline = await get_reputation_timeline(pro.slug)
            s = timeline.signals
            if s.quarantined:
                continue  # provisional role — ineligible for dispatch
            availability = (
                (pro.dispatch_capacity_max - pro.dispatch_capacity_current)
                / pro.dispatch_capacity_max
                if pro.dispatch_capacity_max > 0 else 0.5
            )
            experience = min(s.total_events, 20) / 20.0
            recently = 1.0 if s.recently_active else 0.3
            engagement = min(s.distinct_relationship_types, 5) / 5.0
            score = (
                recently * 0.30 + engagement * 0.25 + experience * 0.20
                + availability * 0.15 + 0.10  # base — everyone gets a floor
            )
            scored.append((round(score, 4), pro))
        except Exception as exc:
            scored.append((0.5, pro))  # timeline computation failed — NOT "no history"

    scored.sort(key=lambda t: t[0], reverse=True)
    return [pro for _, pro in scored]`,
      },
    ],
    theFix: [
      "recently_active is boolean, so it resolves to 1.0 or the 0.3 floor, never an average. experience and engagement scale linearly against a capped denominator (20 events, 5 relationship types) so they floor naturally at 0.0 with no history. Only the except branch — an actual computation failure — falls back to a flat 0.5, and that fallback is deliberately distinguished, in a comment, from what \"no history\" should mean.",
    ],
    whyThisMatters: [
      "Conflating \"we have no data\" with \"something broke\" is a common, easy-to-miss scoring-system bug — both look like a missing number, but they should never resolve to the same score. Treating them differently, and documenting why in the code, is the kind of small, deliberate honesty about what a metric actually means that separates a scoring system that's technically working from one that's actually fair.",
    ],
  },
  {
    slug: "corroborating-weak-signals",
    project: "Farpost",
    category: "Data Ingestion",
    date: "2026-07-15",
    title: "Two Weak Signals Beat One Strong-Looking One",
    framing: [
      "Matching a government address record against Farpost's own building records sounds like a string-matching problem — normalize both addresses and compare. Canada's civic-address data is fragmented enough that string matching alone isn't reliable, so this ingestion path never trusts it alone.",
      "A string match is corroborated by an independent signal: is there a building within 50 meters of the government record's actual coordinates? If both agree, it's a confident match. If the string match says one building but the coordinates say another one two kilometers away, that's not resolved by trusting either signal — it's logged as ambiguous for a human to look at.",
    ],
    codeBlocks: [
      {
        language: "python",
        code: `async def ingest_nar_record(record, building_repo, ambiguity_repo, write_buffer=None) -> str:
    """Returns "matched", "created", or "ambiguous" for caller-side stats."""
    loc_guid = record["loc_guid"]
    location = record.get("location")

    candidates = await building_repo.find_by_normalized_address(
        record["postal_code"], record["civic_no"], record["street_name"],
    )

    if len(candidates) > 1:
        await ambiguity_repo.record(
            loc_guid, "multiple_string_matches", [c.slug for c in candidates], record,
        )
        return "ambiguous"

    if len(candidates) == 1:
        candidate = candidates[0]
        if location is None or candidate.location is None:
            # No location data on one side to corroborate with — still unambiguous.
            await _backfill_match(candidate, loc_guid, location, write_buffer)
            return "matched"
        proximate = await building_repo.find_by_proximity(location, PROXIMITY_RADIUS_METERS)
        if any(str(c.id) == str(candidate.id) for c in proximate):
            await _backfill_match(candidate, loc_guid, location, write_buffer)
            return "matched"
        # String match says one thing, geography says another — don't guess.
        await ambiguity_repo.record(
            loc_guid, "string_match_contradicted_by_proximity", [candidate.slug], record,
        )
        return "ambiguous"

    await _create_building(record, write_buffer)
    return "created"`,
      },
    ],
    theFix: [
      "A single string-match candidate isn't auto-accepted until an independent 50-metre geospatial proximity check corroborates it. No location data on either side falls back to accepting the string match, since there's nothing to contradict it with; a contradiction between the two signals — matched by address, but not by geography — is recorded to an ambiguity repository rather than guessed at, under a different reason code than a genuine multiple-candidate string match.",
    ],
    whyThisMatters: [
      "It's more work to build two independent signals and reconcile disagreements than to trust one, but it's the more defensible choice against genuinely messy, fragmented real-world data. Requiring corroboration instead of trusting either signal alone is a concrete instance of defensive design — the system is built to recognize when it doesn't actually know something, rather than confidently guessing.",
    ],
  },
  {
    slug: "stripe-cache-verification",
    project: "Farpost",
    category: "Payments",
    date: "2026-07-15",
    title: "The Fix That Almost Reopened the Bug It Fixed",
    framing: [
      "Caching a customer's Stripe ID fixed a real race: Stripe's customer-search API is eventually consistent, so searching for \"does this customer already exist\" right after creating them could miss it and create a duplicate. But caching introduced a new, quieter bug — if that customer is later deleted directly in the Stripe dashboard, the cached ID points at nothing, and invoicing breaks with a \"No such customer\" error.",
      "The fix isn't to stop caching — that would reopen the original race. It's to verify the cached ID before trusting it, using a lookup method that doesn't share the same consistency problem the cache was built to avoid.",
    ],
    codeBlocks: [
      {
        language: "python",
        code: `async def resolve_requestor_customer_id(
    cached_customer_id: str | None, email: str, name: str, metadata: dict,
) -> str:
    """Return a valid Stripe customer ID for a requestor, verifying a cached ID still
    resolves before trusting it. A cached ID can go stale if the customer is deleted
    directly in Stripe. customers.retrieve() is an exact, instant-consistent lookup by
    ID, so verifying here doesn't reintroduce the eventually-consistent-search race
    the original caching fix was protecting against."""
    client = _client()
    if cached_customer_id:
        try:
            client.customers.retrieve(cached_customer_id)
            return cached_customer_id
        except stripe.error.InvalidRequestError:
            logger.warning('{"event": "stripe_customer_id_stale", "customer_id": "%s"}',
                            cached_customer_id)
    return await get_or_create_requestor_customer(email=email, name=name, metadata=metadata)`,
      },
    ],
    theFix: [
      "customers.retrieve() looks a customer up by exact ID, which Stripe guarantees is instantly consistent — unlike the search API. Verifying a cached ID with retrieve() before using it catches a stale, deleted ID without reintroducing the eventual-consistency race the cache was originally built to solve. A retrieve() failure falls back to the same get_or_create path used when there was no cached ID at all.",
    ],
    whyThisMatters: [
      "This is a fix within a fix — it required actually understanding why the original caching fix worked (an exact-ID lookup being consistent when a search isn't) well enough to add a new safety check without silently undoing that reasoning. That's root-cause diagnosis applied a second time, to a problem the first fix itself created.",
    ],
  },
  {
    slug: "stripe-pending-invoice-items-footgun",
    project: "Farpost",
    category: "Payments",
    date: "2026-07-15",
    title: "A Stripe Default That Produces a $0 Invoice — Silently",
    framing: [
      "Stripe lets you attach a pending invoice item to a customer, then create an invoice that's supposed to pull it in. What Stripe doesn't do is default to including it — omit one specific parameter and the invoice comes back empty, for $0, and gets auto-marked as paid. No error, no warning. The platform fee that invoice item represented is left sitting nowhere.",
      "A second, related surprise showed up in the same file: a freshly created draft invoice's hosted URL comes back as null. Stripe only fills it in once the invoice is finalized — a caller expecting the link immediately after creation gets nothing, silently.",
    ],
    codeBlocks: [
      {
        language: "python",
        code: `async def create_platform_fee_invoice_draft(customer_id: str, fee_cents: int, description: str) -> str:
    """Create a draft platform fee invoice without finalizing."""
    client = _client()
    client.invoice_items.create(params={
        "customer": customer_id, "amount": fee_cents, "currency": "cad",
        "description": description,
    })
    invoice = client.invoices.create(params={
        "customer": customer_id,
        "collection_method": "send_invoice",
        "days_until_due": 30,
        # Without this, Stripe defaults to "exclude" and the pending invoice item
        # created above never attaches — the invoice comes back empty ($0, auto-marked
        # paid) while the real fee sits stranded.
        "pending_invoice_items_behavior": "include",
    })
    return invoice.id

async def finalize_and_send_platform_fee_invoice(invoice_id: str, fee_cents: int) -> str | None:
    """Confirmed empirically: a draft invoice's hosted_invoice_url is None — Stripe
    only populates it once finalize_invoice() runs."""
    client = _client()
    finalized = client.invoices.finalize_invoice(invoice_id)
    client.invoices.send_invoice(invoice_id)
    return finalized.hosted_invoice_url`,
      },
    ],
    theFix: [
      "pending_invoice_items_behavior: \"include\" has to be passed explicitly when creating the invoice, or Stripe defaults to excluding the pending item that was just created for it. And hosted_invoice_url is only populated after finalize_invoice() runs — a caller has to capture it from that call's return value, not from the draft-creation response.",
    ],
    whyThisMatters: [
      "Both of these were found empirically, not from documentation — a bug that produces zero errors and just quietly returns wrong or missing data is the hardest kind to catch by inspection alone, and the code says outright that it was confirmed by testing against the real API rather than assumed from Stripe's docs. That's verification discipline: not trusting an integration to behave the way its documentation implies, and checking the actual behavior instead.",
    ],
  },
  {
    slug: "webhook-redelivery-idempotency",
    project: "Farpost",
    category: "Payments",
    date: "2026-07-15",
    title: "The Webhook Redelivery Stripe Warns You About",
    framing: [
      "Stripe is explicit that it doesn't guarantee a webhook is delivered exactly once — the same event can arrive twice. Farpost's handler for a paid invoice was overwriting a job's paid-timestamp every single time that event arrived, including on a redelivery of an event it had already processed correctly.",
      "That meant a redelivered, already-handled webhook could silently corrupt a record that was already correct — replacing an accurate paid-date with a later, wrong one, with nothing in the logs to suggest anything had gone wrong.",
    ],
    codeBlocks: [
      {
        language: "python",
        code: `async def _handle_invoice_paid(invoice) -> None:
    """Mark platform_fee_collected on the job when the invoice is settled.

    Stripe does not guarantee at-most-once webhook delivery — a redelivered
    invoice.payment_succeeded was silently overwriting platform_fee_paid_at with a
    later timestamp on every redelivery, corrupting the actual paid-date. Now a
    no-op once already marked collected."""
    invoice_id = invoice["id"]
    job = await Job.find_one({"payment.platform_fee_invoice_id": invoice_id})
    if not job:
        return

    if job.payment.platform_fee_collected:
        return  # already recorded — a redelivery, not a new event

    job.payment.platform_fee_collected = True
    job.payment.platform_fee_paid_at = datetime.now(timezone.utc)
    job.payment.status = PaymentStatus.PAID
    await job.save()`,
      },
    ],
    theFix: [
      "The handler now checks whether the job is already marked platform_fee_collected before doing anything else, and returns immediately if so. A redelivery of an event that already succeeded becomes a no-op instead of a second write, so the paid-date it recorded the first time can't be overwritten by a later, incorrect one.",
    ],
    whyThisMatters: [
      "It's easy to build the happy path for a webhook — event arrives, update the record — and never consider what a second, redundant delivery of the exact same event does to that same update. Recognizing that a webhook handler needs to be idempotent, not just correct on a single delivery, is a specific and easy-to-skip form of defensive design.",
    ],
  },
  {
    slug: "twilio-signature-scheme-mismatch",
    project: "Farpost",
    category: "Notifications",
    date: "2026-07-15",
    title: "When the Infrastructure Lies About Its Own URL",
    framing: [
      "Twilio signs every webhook request with the exact URL it sent that request to, and Farpost validates that signature to make sure a request claiming to be from Twilio actually is. In production, every single validation failed.",
      "The cause was invisible locally: Railway, the hosting platform, terminates HTTPS at its own proxy, so the request arrives at the app internally as plain http://. But Twilio signed the https:// URL it actually called. Validating the signature against the URL the app sees, instead of the URL Twilio used, meant every real request failed a check it should have passed.",
    ],
    codeBlocks: [
      {
        language: "python",
        code: `def _validate_twilio_signature(request: Request, body: dict) -> None:
    """Validate Twilio request signature to prevent spoofed webhook calls."""
    validator = RequestValidator(settings.TWILIO_AUTH_TOKEN)
    signature = request.headers.get("X-Twilio-Signature", "")
    url = str(request.url)
    # Railway terminates TLS at the proxy — internal requests arrive as http,
    # but Twilio signed the https:// URL it actually sent to.
    if url.startswith("http://"):
        url = "https://" + url[7:]

    if not validator.validate(url, body, signature):
        raise HTTPException(status_code=403, detail={"code": "INVALID_SIGNATURE"})`,
      },
    ],
    theFix: [
      "Before validating, the URL's scheme is rewritten from http:// to https:// if it starts with http:// — matching what Twilio actually signed, without touching anything about how the signature itself is checked.",
    ],
    whyThisMatters: [
      "This class of bug is invisible in local development, where there's no TLS termination happening in front of the app at all, and only shows up once the real infrastructure is in the loop — it can't be found by reading code or running tests locally, only by actually deploying and testing against the real thing. Catching and fixing it is a direct demonstration of root-cause diagnosis under a genuinely confusing symptom: a security check failing 100% of the time, for a reason that had nothing to do with the security logic itself.",
    ],
  },
  {
    slug: "fact-staleness-half-life-decay",
    project: "Farpost",
    category: "Data Modeling",
    date: "2026-07-15",
    title: "Not Every Fact Goes Stale at the Same Rate",
    framing: [
      "Not every fact about a building goes out of date at the same speed. Foundation documentation is still probably accurate a decade later; a mechanical inspection is not. Farpost's building records track that directly, instead of flattening every fact into one \"last updated\" timestamp for the whole record.",
      "Each category — foundation, electrical, plumbing, roof, mechanical, and others — has its own half-life, in months, and its own independent staleness clock, so a building can have fresh foundation data and stale mechanical data at the same time, and get renotified about only the part that's actually gone stale.",
    ],
    codeBlocks: [
      {
        language: "python",
        code: `async def upsert_fact_staleness(self, slug: str, category: str, visit_date: date):
    """Resets the category's staleness clock to the new visit_date."""
    building = await self.find_by_slug(slug)
    half_life_months = FACT_STALENESS_HALF_LIFE_MONTHS[category]
    building.fact_staleness[category] = FactStaleness(
        last_documented_at=visit_date,
        half_life_months=half_life_months,
        next_stale_at=_add_months(visit_date, half_life_months),
        notified_at=None,
    )
    await building.save()
    return building

async def get_due_for_fact_decay(self) -> list[Building]:
    """Categories are a small fixed set, so this is a plain $or across each known
    key rather than an aggregation pipeline."""
    today = date.today()
    conditions = [
        {
            f"fact_staleness.{category}.next_stale_at": {"$lt": today},
            f"fact_staleness.{category}.notified_at": None,
        }
        for category in FACT_STALENESS_HALF_LIFE_MONTHS
    ]
    return await Building.find({"$or": conditions}).to_list()`,
      },
    ],
    theFix: [
      "Recording a visit resets that specific category's clock — next_stale_at is set to the visit date plus that category's own half-life (120 months for foundation down to 36 for mechanical). Finding buildings due for renotification is a plain $or across each of the small, fixed set of categories, checking each one's next_stale_at and notified_at independently — deliberately not an aggregation pipeline, since the category list is small and fixed rather than something that grows without bound.",
    ],
    whyThisMatters: [
      "Modeling \"how fast does this specific kind of information actually decay\" instead of collapsing it into one blanket timestamp is a more nuanced, more accurate model of the real problem — and choosing the plain query over a fancier aggregation pipeline, because the actual shape of the data didn't call for one, is its own kind of judgment: knowing when the simpler tool is the correct one, not just the easier one.",
    ],
  },
  {
    slug: "async-safe-claude-integration",
    project: "Farpost",
    category: "AI Integration",
    date: "2026-07-15",
    title: "Respecting the Event Loop When Wiring Up Claude",
    framing: [
      "Part of Farpost's contribution pipeline calls Claude to rewrite evaluative language (\"roof looks bad\") into neutral, observational language (\"roof has visible granule loss\"). The Anthropic SDK's call is synchronous, and Farpost's API is built on an async event loop — calling a blocking network request directly from an async route would stall every other concurrent request on the same process while it waits.",
      "The integration also doesn't fully trust Claude's own output format. Even when asked for JSON, the response sometimes arrives wrapped in a markdown code fence — so instead of trusting a clean parse, the code finds the actual JSON object inside whatever text came back.",
    ],
    codeBlocks: [
      {
        language: "python",
        code: `def _call_claude(raw_text: str, role: str) -> dict:
    """Blocking Anthropic SDK call — always run via asyncio.to_thread(), never directly
    from an async route (a synchronous network call here would block the whole event
    loop, stalling every other concurrent request on this process)."""
    client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)
    message = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=512,
        messages=[{"role": "user", "content": PREEN_PROMPT.format(role=role, raw_text=raw_text)}],
    )
    raw = message.content[0].text.strip()
    # Claude sometimes wraps JSON in markdown code fences — extract just the object
    start = raw.find("{")
    end = raw.rfind("}") + 1
    if start == -1 or end == 0:
        raise ValueError(f"No JSON object found in response: {raw[:100]}")
    return json.loads(raw[start:end])

async def preen_contribution(raw_text: str, role: str) -> dict:
    """Raises on API failure — callers handle the failure path."""
    result = await asyncio.to_thread(_call_claude, raw_text, role)
    return result`,
      },
    ],
    theFix: [
      "The blocking SDK call is wrapped in asyncio.to_thread(), moving it off the event loop entirely, with a comment explaining exactly why — calling it directly from an async route would block every other concurrent request on the process, not just this one. Parsing finds the first { and last } in the raw response text and parses only that slice, rather than assuming the whole response is a clean JSON document.",
    ],
    whyThisMatters: [
      "Both details are the kind that don't show up in a quick demo — a synchronous call blocking an event loop only becomes visible under real concurrent load, and an LLM's occasional code-fence wrapping only shows up after enough real calls. Building an AI feature that respects the runtime it's running on, and doesn't take an LLM's output format on faith, is what real AI-integration experience looks like, versus a feature that only works in the one case it was tested against.",
    ],
  },
];
